Question 1:Create an element-wise comparison (greater, greater_equal, less and less_equal) of two given arrays

In [1]:
import pandas as pd
import numpy as np

In [2]:
x = np.array([29,45,67,80,15,65,75])
y = np.array([32,89,23,12,15,90,76])
print(x,y)

[29 45 67 80 15 65 75] [32 89 23 12 15 90 76]


In [3]:
print(np.equal(x, y))

[False False False False  True False False]


Question 2:Write a NumPy program to create an array of 10 zeros,10 ones, 10 fives

In [4]:
AAA = np.zeros(10)
print(AAA)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [5]:
BBB = np.ones(10)
print(BBB)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [6]:
CCC = np.ones(10)*5
print(CCC)

[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


Question 3:Write a NumPy program to compute sum of all elements, sum of each column and sum of each row of a
given array

In [7]:
xx = np.array([[2,4],[9,5],[8,6]])
print(xx)

[[2 4]
 [9 5]
 [8 6]]


In [8]:
print("The Sum of all Elements is:", xx.sum())

The Sum of all Elements is: 34


In [9]:
print("The Sum of column Elements is:", xx.sum(axis=0))

The Sum of column Elements is: [19 15]


In [10]:
print("The Sum of Row Elements is:", xx.sum(axis=1))

The Sum of Row Elements is: [ 6 14 14]


Question 4:Write a NumPy program to add, subtract, multiply, divide arguments element-wise.

In [11]:
np.sum([25,65])

90

In [12]:
np.subtract(25,65)

-40

In [13]:
np.multiply(25,65)

1625

In [14]:
np.divide(25,65)

0.38461538461538464

Question 5:Write a NumPy program to compute the trigonometric sine, cosine and tangent array of angles given in
degree

In [15]:
angle = int(input("Enter the angle to be calcuated :"))
print("The Sine value of ","angle", "in degrees is:",np.sin(30)*np.pi/180)
print("The Cosine value of ","angle", "in degrees is:",np.cos(30)*np.pi/180)
print("The Tangent value of ","angle", "in degrees is:",np.tan(30)*np.pi/180)

Enter the angle to be calcuated :30
The Sine value of  angle in degrees is: -0.017244404954247373
The Cosine value of  angle in degrees is: 0.002692195676513379
The Tangent value of  angle in degrees is: -0.11179411906218586


Question 6:Write a Pandas program to create and display a DataFrame from a specified dictionary data which has the
index labels

In [16]:
persons  = {'name': ["jacob","john","kennedy","ram","shyam","birbal"],
        'age': [21,22,26,25,30,18],
        'location': ["delhi","mumbai","kolkota","bangalore","hyderabad","delhi"]}

In [17]:
df = pd.DataFrame(persons)
print(df)

      name  age   location
0    jacob   21      delhi
1     john   22     mumbai
2  kennedy   26    kolkota
3      ram   25  bangalore
4    shyam   30  hyderabad
5   birbal   18      delhi


Question 7:Write a Pandas program to select the 'name' and 'score' columns from the following DataFrame.

In [18]:
# As there wasnt any score columns
# As the dataframe was given,i shall consider my dataframe

In [19]:
df[['name','location']]

name   location
0    jacob      delhi
1     john     mumbai
2  kennedy    kolkota
3      ram  bangalore
4    shyam  hyderabad
5   birbal      delhi

Question 8:Write a Pandas program to join the two given dataframes along rows and assign all data.

In [20]:
#Creating another dataframe
persons2  = {'name': ["geetha","pinky","ramya","alex"],
        'age': [18,25,26,19],
        'location': ["bangalore","hyderabad","delhi",np.nan]}
df1 = pd.DataFrame(persons2)

In [21]:
data = pd.concat([df,df1])
print(data)

      name  age   location
0    jacob   21      delhi
1     john   22     mumbai
2  kennedy   26    kolkota
3      ram   25  bangalore
4    shyam   30  hyderabad
5   birbal   18      delhi
0   geetha   18  bangalore
1    pinky   25  hyderabad
2    ramya   26      delhi
3     alex   19        NaN


Question 9:Write a Pandas program to detect missing values of a given DataFrame. Display True or False.

In [22]:
pd.isna(data)

name    age  location
0  False  False     False
1  False  False     False
2  False  False     False
3  False  False     False
4  False  False     False
5  False  False     False
0  False  False     False
1  False  False     False
2  False  False     False
3  False  False      True

Question 10:Write a Pandas program to create and display a one-dimensional array-like object containing an array of
data.

In [23]:
new = pd.Series([25,65,85,71,108])
print(new)

0     25
1     65
2     85
3     71
4    108
dtype: int64


In [24]:
type(new)

pandas.core.series.Series